package common

const (
	ULINE = "_"
	UNCOMFIRM = "UNCONFIRM"
	SYSTEM = "SYSTEM"
	PRODUCT_OWNER = "PRODUCT_OWNER"
	REGISTER = "01"
	CHANGE_OWNER = "02"
	CONFIRM_CHANGE_OWNER = "03"
	CHANGE_PRODUCT = "04"
	DESTROY = "99"
	PRODUCT_INFO = "PRODUCT_INFO"
	PRODUCT_ID = "productId"

)
