---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "halalchain"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Halalchain Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see hlc-test.yml and creater-test.yml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  mychannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer1.hlcorderer.com

    # Required. list of peers from participating orgs
    peers:
      peer1~hlc~com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer2~hlc~com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer1~creater~com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer2~creater~com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer1~transfer~com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer2~transfer~com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer1~seller~com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer2~seller~com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false
    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v1.0

#
# list of participating organizations in this network
#
organizations:
  hlc:
    mspid: hlc

    peers:
      - peer1.hlc.com
      - peer2.hlc.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ica-hlc

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: fabric-ca/halal/orgs/hlc.com/admin/msp/keystore/ADMIN1_PRIVATE_KEY
    signedCert:
      path: fabric-ca/halal/orgs/hlc.com/admin/msp/signcerts/cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  creater:
    mspid: breed
    peers:
      - peer1.creater.com
      - peer2.creater.com
    certificateAuthorities:
      - ica-creater
    adminPrivateKey:
      path: fabric-ca/halal/orgs/creater.com/admin/msp/keystore/ADMIN2_PRIVATE_KEY
    signedCert:
      path: fabric-ca/halal/orgs/creater.com/admin/msp/signcerts/cert.pem

  transfer:
    mspid: butcher
    peers:
      - peer1.transfer.com
      - peer2.transfer.com
    certificateAuthorities:
      - ica-transfer
    adminPrivateKey:
      path: fabric-ca/halal/orgs/transfer.com/admin/msp/keystore/ADMIN3_PRIVATE_KEY
    signedCert:
      path: fabric-ca/halal/orgs/transfer.com/admin/msp/signcerts/cert.pem

  seller:
    mspid: market
    peers:
      - peer1.seller.com
      - peer2.seller.com
    certificateAuthorities:
      - ica-seller
    adminPrivateKey:
      path: fabric-ca/halal/orgs/seller.com/admin/msp/keystore/ADMIN4_PRIVATE_KEY
    signedCert:
      path: fabric-ca/halal/orgs/seller.com/admin/msp/signcerts/cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer1~hlcorderer~com:
    url: grpcs://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer1.hlcorderer.com
      grpc-max-send-message-length: 15

    tlsCACerts:
      path: fabric-ca/halal/hlc-ca-chain.pem

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer1~hlc~com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:7051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:7053

    grpcOptions:
      ssl-target-name-override: peer1.hlc.com
#      clientKey: ../fabric-ca/halal/tls/peer1-hlc-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer1-hlc-cli-client.crt
#      pem: ../fabric-ca/halal/hlc-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/hlc-ca-chain.pem

  peer2~hlc~com:
    url: grpcs://localhost:8051
    eventUrl: grpcs://localhost:8053
    grpcOptions:
      ssl-target-name-override: peer2.hlc.com
#      clientKey: ../fabric-ca/halal/tls/peer2-hlc-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer2-hlc-cli-client.crt
#      pem: ../fabric-ca/halal/hlc-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/hlc-ca-chain.pem

  peer1~creater~com:
    url: grpcs://localhost:9051
    eventUrl: grpcs://localhost:9053
    grpcOptions:
      ssl-target-name-override: peer1.creater.com
#      clientKey: ../fabric-ca/halal/tls/peer1-creater-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer1-creater-cli-client.crt
#      pem: ../fabric-ca/halal/creater-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/creater-ca-chain.pem

  peer2~creater~com:
    url: grpcs://localhost:10051
    eventUrl: grpcs://localhost:10053
    grpcOptions:
      ssl-target-name-override: peer2.creater.com
#      clientKey: ../fabric-ca/halal/tls/peer2-creater-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer2-creater-cli-client.crt
#      pem: ../fabric-ca/halal/creater-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/creater-ca-chain.pem

  peer1~transfer~com:
    # this URL is used to send endorsement and query requests
    url: grpcs://localhost:11051

    # this URL is used to connect the EventHub and registering event listeners
    eventUrl: grpcs://localhost:11053

    grpcOptions:
      ssl-target-name-override: peer1.transfer.com
#      clientKey: ../fabric-ca/halal/tls/peer1-transfer-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer1-transfer-cli-client.crt
#      pem: ../fabric-ca/halal/transfer-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/transfer-ca-chain.pem

  peer2~transfer~com:
    url: grpcs://localhost:12051
    eventUrl: grpcs://localhost:12053
    grpcOptions:
      ssl-target-name-override: peer2.transfer.com
#      clientKey: ../fabric-ca/halal/tls/peer2-transfer-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer2-transfer-cli-client.crt
#      pem: ../fabric-ca/halal/transfer-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/transfer-ca-chain.pem

  peer1~seller~com:
    url: grpcs://localhost:13051
    eventUrl: grpcs://localhost:13053
    grpcOptions:
      ssl-target-name-override: peer1.seller.com
#      clientKey: ../fabric-ca/halal/tls/peer1-seller-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer1-seller-cli-client.crt
#      pem: ../fabric-ca/halal/seller-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/seller-ca-chain.pem

  peer2~seller~com:
    url: grpcs://localhost:14051
    eventUrl: grpcs://localhost:14053
    grpcOptions:
      ssl-target-name-override: peer2.seller.com
#      clientKey: ../fabric-ca/halal/tls/peer2-seller-cli-client.key
#      clientCert: ../fabric-ca/halal/tls/peer2-seller-cli-client.crt
#      pem: ../fabric-ca/halal/seller-ca-chain.pem
    tlsCACerts:
      path: fabric-ca/halal/seller-ca-chain.pem


#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ica-hlc:
    url: https://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: fabric-ca/halal/hlc-ca-chain.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: ica-hlc-admin
        enrollSecret: ica-hlc-adminpw
    # [Optional] The optional name of the CA.
    caName: ica-hlc

  ica-creater:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: fabric-ca/halal/creater-ca-chain.pem
    registrar:
      - enrollId: ica-creater-admin
        enrollSecret: ica-creater-adminpw
    # [Optional] The optional name of the CA.
    caName: ica-creater

  ica-transfer:
    url: https://localhost:9054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: fabric-ca/halal/transfer-ca-chain.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: ica-transfer-admin
        enrollSecret: ica-transfer-adminpw
    # [Optional] The optional name of the CA.
    caName: ica-transfer

  ica-seller:
    url: https://localhost:10054
    httpOptions:
      verify: false
    tlsCACerts:
      path: fabric-ca/halal/seller-ca-chain.pem
    registrar:
      - enrollId: ica-seller-admin
        enrollSecret: ica-seller-adminpw
    # [Optional] The optional name of the CA.
    caName: ica-seller
