# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  halal:
services:
  ca0:
    image: hyperledger/fabric-ca:x86_64-1.1.0-alpha
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hlc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hlc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hlc.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerOrg1
    networks:
      - halal

  ca1:
    image: hyperledger/fabric-ca:x86_64-1.1.0-alpha
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.creater.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.creater.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/creater.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerOrg2
    networks:
      - halal

  ca2:
    image: hyperledger/fabric-ca:x86_64-1.1.0-alpha
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.transfer.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.transfer.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/transfer.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerOrg3
    networks:
      - halal

  ca3:
    image: hyperledger/fabric-ca:x86_64-1.1.0-alpha
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.seller.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.seller.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/seller.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./channel-artifacts/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerOrg4
    networks:
      - halal

  orderer0.hlcorderer.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.hlcorderer.com
    container_name: orderer0.hlcorderer.com
    networks:
      - halal

  peer0.hlc.com:
    container_name: peer0.hlc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hlc.com
    networks:
      - halal

  peer1.hlc.com:
    container_name: peer1.hlc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hlc.com
    networks:
      - halal

  peer0.creater.com:
    container_name: peer0.creater.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.creater.com
    networks:
      - halal

  peer1.creater.com:
    container_name: peer1.creater.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.creater.com
    networks:
      - halal

  peer0.transfer.com:
    container_name: peer0.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.transfer.com
    networks:
      - halal

  peer1.transfer.com:
    container_name: peer1.transfer.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.transfer.com
    networks:
      - halal

  peer0.seller.com:
    container_name: peer0.seller.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.seller.com
    networks:
      - halal

  peer1.seller.com:
    container_name: peer1.seller.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.seller.com
    networks:
      - halal

  config:
    container_name: config
    image: grapebaba/config-server-template
    ports:
      - "8888:8888"
    volumes:
        - ./../config:/config
    networks:
      - halal
